{
 "title": "Neighborhood AQI",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "sensor_name", "query": "label_values(sensor_name)" }
  ]
 },
 "panels": [
  { "title": "Current AQI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current PM 2.5 AQI",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(purpleair_pm_25_10m_iaqi{sensor_name=~\"^$sensor_name$\"})\n"
    }
   ]
  },
  {
   "title": "Current PM 2.5 AQI (AQandU)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(purpleair_pm_25_10m_iaqi_AQandU{sensor_name=~\"^$sensor_name$\"})\n"
    }
   ]
  },
  {
   "title": "Current PM 2.5 AQI (LRAPA)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(purpleair_pm_25_10m_iaqi_LRAPA{sensor_name=~\"^$sensor_name$\"})\n"
    }
   ]
  },
  { "title": "AQI History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PM 2.5 AQI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(purpleair_pm_25_10m_iaqi{sensor_name=~\"^$sensor_name$\"})\n",
     "legendFormat": "PA AQI"
    },
    {
     "expr": "max(purpleair_pm_25_10m_iaqi_AQandU{sensor_name=~\"^$sensor_name$\"})\n",
     "legendFormat": "AQandU AQI"
    },
    {
     "expr": "max(purpleair_pm_25_10m_iaqi_LRAPA{sensor_name=~\"^$sensor_name$\"})\n",
     "legendFormat": "LRAPA AQI"
    }
   ]
  }
 ]
}